### ISSUE TITLE
Scroll Bars on Windows

### ISSUE THREAD

**Issue by brainsandspace** [webmatze/hyperborder#18] opened 2016-12-19 03:18 UTC
I  was getting scroll bars on Windows 10.

![image](https://cloud.githubusercontent.com/assets/6373939/21299957/43bc0016-c56e-11e6-8ad3-f7a4a2204c77.png)

So I set 
```
html {
  overflow: hidden;
}
```
which seemed to do the trick. Creating a PR. #19

**Comment by webmatze** [comment] 2016-12-20 20:47
Thank you for your contribution. I just merged you PR and published a new version of hyperborder.
Can you confirm that the problem is now fixed?

**Closed** 2016-12-21 20:55 UTC

**Comment by brainsandspace** [comment] 2016-12-25 06:50
confirmed

*David Baker*

University of Pennsylvania | Class of 2015

School of Engineering and Applied Sciences
847.702.1540 | drbaker2@gmail.com
